# Generated by Django 4.2 on 2023-06-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('P', 'OVO'), ('S', 'Dana')], max_length=1),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('S', 'Souvenir & Merchandise'), ('SW', 'Fashion'), ('OW', 'Craft')], max_length=2),
        ),
    ]
