# Generated by Django 4.2 on 2023-06-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_alter_payment_payment_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('S', 'Script')], max_length=1),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('S', 'Obat-obatan'), ('SW', 'Perawatan Tubuh'), ('OW', 'Alat Kesehatan')], max_length=2),
        ),
    ]
